[package]
name = "usereventsourcing"
version = "0.1.0"
authors = ["rsb007 <rahul.sing@knoldus.in>"]

[dependencies]
cdrs = "2.0.0-beta.3"
json = "*"
uuid = { version = "0.4.0", features = ["serde", "v4"] }